ESMCI/ccs_config_cesm

- machines/config_pio.xml
Reverts ESMCI/ccs_config_cesm#13
> Revert "force cice to use box rearranger due to bug in pio255"

- machines/config_pio.xml
Set io to netcdf for scam compset.
> set scam io to netcdf

- component_grids_nuopc.xml
Hopefully the last update needed for https://github.com/ESCOMP/CAM/pull/556
> fix typo in ne5pg2 mesh name

- machines/config_machines.xml
Note that this PR requires https://github.com/ESMCI/cime/pull/4201
Define a container environment on cheyenne.   See
https://github.com/ESCOMP/CESM/wiki/Using-CESM-in-the-Cray-environment-container-on-Cheyenne
for a usage description.   This is a prototype that I think can be extended to other systems and
other containers.
> add support for running in containers

- machines/config_machines.xml
Fix esmf module path for nvhpc on cheyenne.
> Fix esmf module path for nvhpc on cheyenne.

- machines/config_machines.xml
- modelgrid_aliases_nuopc.xml
Remove the CPE machine now that gust has arrived, update some cheyenne modules, add some refined grids.
> add some refined grids update some cheyenne modules

- machines/config_batch.xml
Updates config batch to use `<argument>` instead of `<arg>` which allows for queue specific flags.
> updates arg to argument in config_batch.xml, see cime PR #4307

- machines/config_machines.xml
Update to latest esmf development beta.
> update esmf on cheyenne to 8.4.0b18

- machines/config_machines.xml
Update cheyenne esmf library to 8.4 release.
> Update cheyenne esmf library to 8.4 release.

- machines/config_machines.xml
Update frontera intel modules and update esmf library to 8.4.0b21.
> Update frontera intel modules and esmf library.

- machines/config_machines.xml
On Cheyenne, update ESMF to 8.4.1b02 and PIO to 2.5.10.
> Update cheyenne esmf library to 8.4.1b02

- machines/config_machines.xml
- modelgrid_aliases_nuopc.xml
Update ESMF and PIO libraries for fontera.  Also add mpasa3p75_mpasa3p75_mt13 grid alias.
> Update esmf/pio and add grid alias for 3.75km mpas.

- component_grids_nuopc.xml
- modelgrid_aliases_nuopc.xml
Add ne3pg3_ne3pg3_mg37 grid.
Tested with SMS_Ln9.ne3pg3_ne3pg3_mg37.A.cheyenne_intel.
New mesh file has to imported to repository.
Resolves issue #76
> Add ne3pg3_ne3pg3_mg37 grid.

- modelgrid_aliases_nuopc.xml
> remove _CLM from not_compset for ne16 grid

- machines/config_machines.xml
Update ESMF library on cheyenne and izumi to the 8.5.0 release.
> Update ESMF library to 8.5.0 release on cheyenne and izumi.

- machines/config_batch.xml
Adds support for job priority on derecho.
> support for job priority on derecho

- machines/config_machines.xml
updates pio on derecho from 2.6.0 to 2.6.2
> update pio module on derecho

- machines/config_machines.xml
Updates modules on derecho for ncarenv/23.09
> update modules for derecho

- machines/casper/config_machines.xml
- machines/cmake_macros/derecho.cmake
- machines/config_batch.xml
Ncar updates again with new config_machines.xml format.
> replaces ncar_updates_231206

- machines/config_batch.xml
- machines/frontera/config_machines.xml
Updates batch and modules for tacc frontera.
> update modules and batch for tacc frontera

- component_grids_nuopc.xml
- modelgrid_aliases_mct.xml
- modelgrid_aliases_nuopc.xml
Updated polarcap path, re-did PR https://github.com/ESMCI/ccs_config_cesm/pull/158 @jedwards4b 
Fixes #152 
Fixes #153
> redo polarcap/mpas grid fix PR

- machines/izumi/config_machines.xml
Update the python interpreter used on izumi
> update python version on izumi

- machines/perlmutter/config_machines.xml
updates for the perlmutter system at nersc
> updates for perlmutter

- component_grids_nuopc.xml
- modelgrid_aliases_nuopc.xml
I have added the grid gx3v7 for WW3 here.
> Add gx3v7 grid for WW3

- config_archive.xml
Remove obsolete references to archive files.
> remove obsolete specs

- machines/derecho/config_batch.xml
This should help to speed up submitted jobs on derecho.
> removes explicit mem check for derecho

- machines/izumi/config_machines.xml
Update ESMF to version 8.6.1 on izumi.
> Update ESMF to version 8.6.1 on izumi.

- machines/izumi/nag_izumi.cmake
need an rpath for nag on izumi
> fix for izumi nag build

- config_inputdata.xml
Updating to accommodate current NCAR data access policy.
> remove anonymous ftp and gridftp, use wget

- maps_nuopc.xml
Fixes a typo in the filename introduced in https://github.com/ESMCI/ccs_config_cesm/pull/201
> Fix typo, sm ~> nnsm

- component_grids_nuopc.xml
testing: SMS_Ld2.TL319_t232_wg37.GW_JRA.derecho_gnu (bfb)
> Update wg37 mesh to cdf5

- machines/casper/config_batch.xml
- machines/casper/config_machines.xml
This PR updates the Casper machine and batch configuration for memory request, which allows to share a node with the changes from https://github.com/ESMCI/cime/pull/4781.
> Update Casper machine and batch configurations

- machines/derecho/config_machines.xml
Support for FTORCH library, and updates for esmf, parallelio and netcdf on derecho.
> update to add ftorch and update esmf, netcdf and parallelio for intel

- machines/cmake_macros/CMakeLists.txt
- machines/cmake_macros/Macros.cmake
Need to add the cmake policy cmake_policy(SET CMP0057 NEW) here to apply in cprnc build.
> need this policy here for build of cprnc

- modelgrid_aliases_nuopc.xml
Add MOM mt232 masks for cam testing with F compsets.
> add mpasa120_mpasa120_mt232

- machines/config_machines.xml
- machines/perlmutter/config_machines.xml
> perlmutter_update

- machines/derecho/config_machines.xml
- machines/izumi/config_machines.xml
- machines/izumi/gnu_izumi.cmake
Updates gnu compiler to 12.4.0 on Izumi
> update to gnu 12.4.0

- machines/config_workflow.xml
Add override support in config_workflow.xml for mem_per_task variable set in config_machines.xml
> add support for mem_per_task
