ESMCI/ccs_config_cesm

machines/cmake_macros/nvhpc_cheyenne.cmake, machines/config_machines.xml
We now have pio/2.5.5 installed on cheyenne for all of the compiler flavors, I will put up a PR in ccs_config adding the module load.   There is an ESMF branch about to be folded into development with an update to pio2.  Once that is done we will want to build the esmf module with ESMF_PIO=external and using the pio module.  
=> add a pio 2.5.5 module on cheyenne, add nvhpc compiler support

machines/config_pio.xml
Force cice to use PIO_REARRANGER=1
=> force cice to use box rearranger due to bug in pio255

machines/config_machines.xml
Updates pio module on cheyenne and adds for casper.  Now using pio/2.5.6 and pio/2.5.6d
=> use pio/2.5.6 on cheyenne and casper

machines/config_machines.xml
Load the pio/2.5.6 module when mpi-serial is used on cheyenne.
Update the cray container on cheyenne.
=> load module for pio and mpi-serial

machines/config_machines.xml
Update version of nvhpc to 22.2 on cheyenne.  Needed to do this to use pio/2_5_6 module.
=> Update version of nvhpc for cheyenne

machines/Depends.pgi-gpu, machines/config_machines.xml
There is an AVX link issue between the old NVHPC compiler and OpenMPI lib, which will cause a runtime error when using the ESMF lib in the NUOPC driver.
After upgrading NVHPC to NVHPC/22.2 and re-building the ESMF lib on Casper, the runtime error is gone.
Also change the PUMAS file names in the Depends file for PGI compiler.
This PR fixes this issue https://github.com/ESMCI/ccs_config_cesm/issues/11.
Code review: @jedwards4b
=> Update ESMF lib built by NVHPC/22.2

machines/config_machines.xml
The pio module on Casper can not be loaded correctly without specifying the MPI lib and a compilation error would occur when building a CAM test case (fail at the step to build `cprnc`).
=> Add mpilib to load pio correctly on Casper

modelgrid_aliases_nuopc.xml
Add an alias for ne30pg3_t061 grid for cam se dycore used with mom ocean.
=> add alias for model grid

machines/cmake_macros/intel_aws-hpc6a.cmake, machines/config_batch.xml, machines/config_compilers.xml, machines/config_machines.xml
This is an initial port to the AWS infrastructure for CESM, and specifically the HPC6a nodes.
=> Initial AWS HPC6a config

machines/config_machines.xml
Get MPILIB=openmpi to work on cheyenne_intel
Fixes #26
Testing:
built/ran the test SMS_Mopenmpi_D_Ld3.f10_f10_mg37.I1850Clm50BgcCrop.cheyenne_intel.clm-default
under ctsm5.1.dev090 with ccs_config based off of ccs_config_cesm0.0.21
PASS SMS_Mopenmpi_D_Ld3.f10_f10_mg37.I1850Clm50BgcCrop.cheyenne_intel.clm-default CREATE_NEWCASE
PASS SMS_Mopenmpi_D_Ld3.f10_f10_mg37.I1850Clm50BgcCrop.cheyenne_intel.clm-default XML
PASS SMS_Mopenmpi_D_Ld3.f10_f10_mg37.I1850Clm50BgcCrop.cheyenne_intel.clm-default SETUP
PASS SMS_Mopenmpi_D_Ld3.f10_f10_mg37.I1850Clm50BgcCrop.cheyenne_intel.clm-default SHAREDLIB_BUILD time=252
PASS SMS_Mopenmpi_D_Ld3.f10_f10_mg37.I1850Clm50BgcCrop.cheyenne_intel.clm-default MODEL_BUILD time=55
PASS SMS_Mopenmpi_D_Ld3.f10_f10_mg37.I1850Clm50BgcCrop.cheyenne_intel.clm-default …
=> Fix for #26 for compiling/running with openmpi on cheyenne_intel

machines/config_machines.xml, machines/config_pio.xml
This PR just adds a single environment variable (ESMFMKFILE) to the 'aws-hpc6a' config.
=> Added a single environment variable (ESMFMKFILE) needed for CESM2.3+

machines/config_machines.xml
ESMF 8.3.0b13 is experiencing slow-downs.  So I would like to revert the ESMF library update, from PR #30.  This is just 
for cheyenne, I'm leaving the updates for casper.
=> Revert PR #30 for cheyenne

machines/config_batch.xml, machines/config_machines.xml
This PR changes several more things related to the AWS environment.  It:
1) Adds additional queues (for compiling and serial runs, both of which keep costs down)
2) Makes the inputdata be a central location, vs a user-specific one (on the system, we use a sticky bit with group permissions so anyone in the group can write to it, but not overwrite other files -- in short, multiple people can download input data)
3) Changes GMAKE_J to 8 to take advantage of the 8-core build queue
4) Sets MAX_GPUS_PER_NODE to 1, even though we aren't using GPUs, as a way of silencing a warning during 'run_neon'.
5) Configures launching in the serial queue via the unsetting of an environment variable that's necessary for good performance on AWS's HPC nodes, but crashes MPI on nodes without EFA (Elastic Fabric …
=> Additional AWS changes 

machines/config_machines.xml
This PR fixes an issue on Casper that fails to output the timing summary file when using the NUOPC driver.
Following @jedwards4b's suggestions, two environment variables are added.
=> Add ESMF env for Casper to output timing file correctly

machines/template.case.run, machines/template.case.test, machines/template.st_archive
Fixes #45 . See description there for details.
Testing: ran the following tests from CTSM master with ccs_config updated to this branch:
- SMS_D_Ld1.f10_f10_mg37.I1850Clm50BgcCrop.cheyenne_gnu.clm-default (run via create_test)
- SMS_Ld5_D_P48x1.f10_f10_mg37.IHistClm51Bgc.izumi_nag.clm-decStart (run via run_sys_tests)
=> Fix path to CIME tools

machines/config_pio.xml
The previously added aws settings were being activated on all systems because mach attribute was
used in the wrong place.  We probably need better testing and error checking for this.
=> correct way to add aws settings

machines/config_machines.xml
Update ESMF libraries to 8.4.0b08 on cheyenne and casper.
Also update some netcdf-mpi/pnetcdf/openmpi/mpt modules.
=> Update esmf libraries to latest snapshot

machines/config_machines.xml
Add pnetcdf module load for gnu/openmpi on cheyenne.
Fixes #57
=> Add pnetcdf module for gnu/openmpi on cheyenne

machines/config_machines.xml
Update Cheyenne esmf libraries to 8.4.1b01.  
For compilers: intel, gnu, nvhpc
For mpilibs     : mpt, openmpi, mpiuni
=> Update Cheyenne esmf libraries to 8.4.1b01.

machines/config_batch.xml
This corrects the group_list settings for pleiades machines.  The extra white space caused problems.
=> pleiades machines updates

machines/config_machines.xml
Update ESMF libraries to 8.4.1b05 and remove pgi support for izumi.
=> Update esmf libraries and remove pgi on izumi

component_grids_nuopc.xml
The  fv4x5_050615_polemod_ESMFmesh.nc on cheyenne was cdf5 but in the subversion data server it was not.
So trying to use it on other machines failed. A new file fv4x5_050615_polemod_ESMFmesh_cdf5.nc has been created on both cheyenne and imported to the data servers. This PR now references the new file.
=> make 4x5 mesh cdf5

config_inputdata.xml
This PR includes changes that allow PRISM precipitation to be used as a new datm stream.
This PR's functionality also depends on the [PRISM PRECIP CTSM PR](https://github.com/ESCOMP/CTSM/pull/1954), PRISM [PRECIP CDEPS PR](https://github.com/ESCOMP/CDEPS/pull/219), and input data availability. 
Contributors other than yourself, if any: @jedwards4b
=> [WIP] Include PRISM precipitation datm streams

machines/config_machines.xml
This PR updates the version of CMake used on Cheyenne to 3.22.0. The newer version is needed for [CAM PR 784](https://github.com/ESCOMP/CAM/pull/784)
(This is my first PR on this repo, so apologies if this is not the correct way to make this change)
=> update CMake module for Cheyenne

machines/config_machines.xml
Update ESMF libraries on cheyenne to 8.5.0b19.  Because of a slow down with mpt/2.25 for intel, switch the intel
compiler to use mpt/2.22.  The ESMF and PIO libaries for intel were built using mpt/2.22.
=> Update cheyenne esmf libraries to 8.5.0b19, and use mpt/2.22 for intel.

machines/config_machines.xml
Update ESMF to version 8.4.1 on pleiades machines
Testing:
```
SMS_D_Ln9_Vnuopc.f19_f19_mg17.FX2000.pleiades-bro_intel.cam-outfrq9s (Overall: PASS) details:
SMS_D_Ln9_Vnuopc.f19_f19_mg17.FX2000.pleiades-has_intel.cam-outfrq9s (Overall: PASS) details:
SMS_D_Ln9_Vnuopc.f19_f19_mg17.FX2000.pleiades-ivy_intel.cam-outfrq9s (Overall: PASS) details:
SMS_D_Ln9_Vnuopc.f19_f19_mg17.FX2000.pleiades-san_intel.cam-outfrq9s (Overall: PASS) details:
SMS_Ld1.f19_f19_mg17.FX2000.pleiades-bro_intel.cam-outfrq1d (Overall: PASS) details:
SMS_Ld1.f19_f19_mg17.FX2000.pleiades-ivy_intel.cam-outfrq1d (Overall: PASS) details:
```
=> update esmf lib for pleiades

component_grids_nuopc.xml, maps_nuopc.xml, modelgrid_aliases_nuopc.xml
Add the new MOM6 domain tx2_3v2, as well as resolution definitions and map files. This Pr should be evaluated in conjunction with https://github.com/ESCOMP/MOM_interface/pull/141
=> Add new MOM6 grid tx2_3v2

machines/Depends.intel-oneapi, machines/cmake_macros/intel-oneapi.cmake, machines/cmake_macros/intel-oneapi_derecho.cmake, machines/config_machines.xml, machines/config_pio.xml
Replace MPICH_COLL_SYNC=1 with 
FI_MR_CACHE_MONITOR=memhooks.  
See https://support.hpe.com/hpesc/public/docDisplay?docId=a00129146en_us&docLocale=en_US
for details - this new env variable seems to work better than the MPICH_COLL_SYNC.
=> Derecho updates 071223

machines/config_machines.xml
For derecho,
BASELINE_ROOT was set to ccsm_baselines, it should be cesm_baselines.
Also update ESMF library to ESMF8.6.0b03.
=> Change baseline path from ccsm to cesm, and update ESMF of derecho

machines/config_batch.xml
According to many feedback, removing the `-V` option from PBS resource will lead to an error like below on Cheyenne:
> File "/var/spool/pbs/mom_priv/jobs/[3309939.chadmin1.ib0.cheyenne.ucar.edu.SC](http://3309939.chadmin1.ib0.cheyenne.ucar.edu.sc/)", line 20, in <module>
>     from standard_script_setup import *
>   File "/glade/u/home/cacraig/cam_misc_tag/cime/CIME/Tools/standard_script_setup.py", line 33, in <module>
>     check_minimum_python_version(3, 6)
>   File "/glade/u/home/cacraig/cam_misc_tag/cime/CIME/Tools/standard_script_setup.py", line 30, in check_minimum_python_version
>     ), msg
> AssertionError: Python 3, minor version 6 is required, you have 3.4
The `-V` option is removed by PR https://github.com/ESMCI/ccs_config_cesm/pull/97 because the `NGPUS` env variable is not …
=> Add "-V" option back to avoid a python issue on Cheyenne

machines/Depends.cray, machines/Depends.gnu, machines/Depends.intel
In order to build CAM with the RRTMGP code for hybrid parallelization, it is necessary to disable the openmp directives in several RRTMGP files. That's because those directives are intended for running on GPUs and not for use of threads on CPUs.  The compilation fails in the RRTMGP files when trying to build for hybrid mode.
=> build RRTMGP code w/ -fno-openmp option

machines/derecho/config_machines.xml
This PR introduces the system-wide `mpibind` wrapper script on Derecho, which will handle the MPI-only and hybrid MPI/OpenMP configurations automatically. The performance between the MPI-only and hybrid MPI/OpenMP configurations for the `F2000climo` compset and `f09_f09_mg17` grid is comparable on Derecho by using this script.
However, my tests indicate that the threading option in CAM does not work for the `f19_f19_mg17` grid (no matter using the `mpibind` script or manually adding the MPI arguments to the `mpiexec` command). According to the error message shown below, this is likely a code issue rather than a problem from the MPI/OpenMP configuration.
```
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source …
```
=> Use the system-wide MPI wrapper script on Derecho

machines/derecho/config_machines.xml
Workaround the mpi-serial link issue by not using the debug build of pio and esmf when building with mpi-serial.  
Fixes #130
=> workaround mpi-serial debug issue on derecho

machines/derecho/config_machines.xml
Since `ncarenv/23.09`, the MPI+GPU wrapper script on Derecho becomes `set_gpu_rank` and `get_local_rank` is deprecated. This is just a name change and its functionality remains the same.
=> Update the gpu wrapper script on Derecho

machines/derecho/config_machines.xml
The esmf and parallelio module commends weren't being set when compiling with DEBUG turned on, and not using
mpi-serial.
=> Fix esmf/parallelio debug module settings for derecho.

machines/config_batch.xml
Use the develop queue on derecho for st_archive, this is a shared queue and
avoids using a full node for this simple task.
Tested using ERR.f19_g17.A.derecho_intel.
=> change the queue used for st_archive on derecho

machines/Depends.cray, machines/config_batch.xml
I removed the -V option from all NCAR machines and added it to all non-NCAR pbs machines.   I also removed a number of obsolete entries from the file.   
This fixes https://github.com/ESMCI/cime/issues/4594
=> Pbs v removed

machines/Depends.nvhpc, machines/derecho/config_machines.xml
This PR:
- updates the NVHPC compiler version to `nvhpc/24.3` on Derecho, which fixes the `EOSHIFT` bug reported at https://github.com/ESCOMP/CAM/issues/883.
- enables the GPU flags for a new source code in PUMAS so that the `tau` warm rain scheme runs correctly on the GPU.
- updates the CUDA linker flags on Derecho when the GPU options are enabled.
- removes unused env variable for RRTMGP GPU code.
=> Update the GPU settings on Derecho

component_grids_nuopc.xml, modelgrid_aliases_mct.xml, modelgrid_aliases_nuopc.xml
Fixes #152 
Fixes #153 
I verified the new POLARCAP grid alias builds and run with this new ccs_config external. Would someone mind adding the mesh and scrip files to inputdata/share/? Ill then update the paths.
```
/glade/work/aherring/grids/var-res/ne0np4.POLARRES.ne30x4/grids/polarcap/POLARCAP_ne30x4_np4_MESH_cdf5.nc
/glade/work/aherring/grids/var-res/ne0np4.POLARRES.ne30x4/grids/polarcap/POLARCAP_ne30x4_np4_SCRIP.nc
```
Should I first add a creation date to the grid file names? Who should I assign as a reviewer?
=> add polarcap grid, fix mpasa15-3 naming issues

modelgrid_aliases_nuopc.xml
This is a relatively low priority PR, but an easy one too. If we want to run with active glaciers in CESM3 simulations, we will need grid aliases for the common CESM3 grids plus glaciers. I have added some options here for testing as we get closer.
I tested these in the CISM-Wrapper repo (IG cases), but I haven't tested with a full B1850G in CESM yet. Let me know if that is necessary.
=> Adding glc supporting grid aliases for CESM3

modelgrid_aliases_nuopc.xml
</model_grid> was missing from [modelgrid_aliases_nuopc.xml](https://github.com/ESMCI/ccs_config_cesm/compare/fischer/fix_grid_file?expand=1#diff-9c54f8ced6fc32c326ea51cac0a62a8671904a32243ee2bfc8e2064eec9c50a7)
=> Add missing </model_grid> to modelgrid_aliases_nuopc.xml

machines/Depends.nvhpc
These changes were tested on Derecho with
- cam tag: cam6_3_155
- clubb tag: clubb_4ncar_20240605_73d60f6  (https://github.com/larson-group/clubb_release/releases/tag/clubb_4ncar_20240605_73d60f6)
- ccs_config tag: ccs_config_cesm0.0.106
- nvhpc version: 24.3
- resolution: ne30pg3_ne30pg3_mg17
- compset: F2000dev
- addition parameters:  --ngpus-per-node 4 --gpu-type a100 --gpu-offload openacc
=> Making additions to Depends.nvhpc to enable GPU compilation of clubb code.

component_grids_nuopc.xml, modelgrid_aliases_nuopc.xml
Miscellaneous MOM6 and WW3 grid updates. 
- Remove the old mom6 and ww3 grids and aliases t061.
- Add new ww3 grid (based on mom6 grid): wtx2_3v2 
- Add new aliases including wg37 and wt232 ww3 grids.
- Remove `T.*_g1?` POP/MOM grid aliases.
- Change `not_compset=_POP` clauses to `_MOM`
testing: aux_mom, aux_ww3 test suites on derecho.
=> MOM and WW3 grid updates

machines/derecho/config_batch.xml
So, e.g., tests with `128x1` go to main instead of develop. However, `64x2` would still go to develop—not sure if that's what we want.
Resolves #182.
=> Derecho runs requesting ≥64 jobs go to main, not develop

modelgrid_aliases_nuopc.xml
Instead of the short name, we need to specify the full grid name as the default.
=> fix the default grid name for wav components

maps_nuopc.xml
Updated the mapping file to use a 250 km e-folding scale and radius of spreading.
This PR addresses https://github.com/ESCOMP/MOM_interface/issues/209.
=> Update JRA to tx2_3v2 Mapping File

modelgrid_aliases_nuopc.xml
mask information was  needed to run an I-case with the f09_t232 grid.  Is this true for other grids too?
=> enable t232 mask on default land grid

modelgrid_aliases_nuopc.xml
Add grid for CAM F and QP compsets which uses the MOM ocean mask for consistency with B compset mask.
=> add ne30pg3_ne30pg3_t232

machines/config_workflow.xml, machines/template.cupid
This PR will provide updates to `template.cupid` in order to utilize additional xml variables which provide more flexibility for running CUPiD via the CESM workflow.
=> Updates in template.cupid and config_workflow.xml for cupid workflow

config_inputdata.xml
Adds a server in Toronto as a backup inputdata server should NCAR go offline for any reason.
=> add toronto backup for inputdata

machines/derecho/config_machines.xml
Reverts gcc compiler to gcc/12.2.0 due to an issue found in cice in SMS_D.ne30pg3_t232.BLT1850.derecho_gnu.allactive-defaultio
=> Backout gcc update

modelgrid_aliases_nuopc.xml
Add `not_compset="_MOM"` for resolutions that are bot supported by MOM6.
=> Specify not_compset attribute for non-MOM6 resolutions

modelgrid_aliases_nuopc.xml
Continue to replace POP masks by MOM mt232 for cam testing with F compsets.
=> Add F compset grids w/ mt232 mask

modelgrid_aliases_nuopc.xml
The aliases C48_C48_mg17, C96_C96_mg17, C192_C192_mg17 have all somehow been overwritten with C24_C24_mg17.
=> fix aliases for C48_C48_mg17, C96_C96_mg17, C192_C192_mg17

machines/config_workflow.xml
We would like to increase the default wallclock time for running CUPiD.
[Relevant issue](https://github.com/NCAR/CUPiD/issues/245)
=> Increase default wallclock time for cupid

machines/template.cupid
Users may want to use a version of CUPiD that is different from what is in tools/CUPiD -- they can set CUPID_ROOT to point to that location, and should expect cesm_postprocessing.sh to be launched from that location as part of the workflow
Note that the CESM tag that brings in this PR will also need CUPiD to be update to include https://github.com/NCAR/CUPiD/pull/263
=> Use cesm_postprocessing.sh from CUPID_ROOT

config_inputdata.xml
Moves the primary inputdata server from https://ftp.cgd.ucar.edu/cesm/inputdata/
to https://osdf-data.gdex.ucar.edu/ncar/gdex/d651077/cesmdata/inputdata/
=> moves the primary inputdata server to cisl rda

machines/Depends.nvhpc, machines/casper/config_machines.xml
This PR:
- updates the modules on Casper with correct version.
- adds the missing `pumas_gamma_function.F90` code to be compiled with correct GPU flags.
=> Update Casper module version and add a missing PUMAS GPU code
